parser: babel-eslint
extends: airbnb
rules:
  'react/jsx-filename-extension': [1, { 'extensions': ['.js', '.jsx'] }]
  'react/prefer-stateless-function': 0
  'max-len': 0
  "react/forbid-prop-types": 0
  "react/jsx-one-expression-per-line": 0
  "react/react-in-jsx-scope": 0
